In [2]:
import numpy as np
import random
from time import sleep
def create_board():
    return np.zeros((3, 3), dtype=int)
def possibilities(board):
    return [(i, j) for i in range(3) for j in range(3) if board[i, j] == 0]
def random_place(board, player):
    selection = possibilities(board)
    if selection:
        current_loc = random.choice(selection)
        board[current_loc[0], current_loc[1]] = player
    return board
def check_win(board, player):
    return (
        np.any(np.all(board == player, axis=0)) or  # Check columns
        np.any(np.all(board == player, axis=1)) or  # Check rows
        np.all(np.diag(board) == player) or  # Check main diagonal
        np.all(np.diag(np.fliplr(board)) == player)  # Check secondary diagonal
    )
def evaluate(board):
    for player in [1, 2]:
        if check_win(board, player):
            return player  # Return winning player
    return -1 if np.all(board != 0) else 0  # -1 for draw, 0 for ongoing game
def play_game():
    board, winner, counter = create_board(), 0, 1
    print("Initial Board:\n", board)
    sleep(2)
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"Board after move {counter} by Player {player}:\n", board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    if winner == -1:
        print("Game ended in a draw!")
    else:
        print(f"Winner is Player {winner}!")
    return winner
# Driver Code
play_game()


Initial Board:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after move 1 by Player 1:
 [[0 0 0]
 [1 0 0]
 [0 0 0]]
Board after move 2 by Player 2:
 [[0 2 0]
 [1 0 0]
 [0 0 0]]
Board after move 3 by Player 1:
 [[0 2 0]
 [1 0 0]
 [0 1 0]]
Board after move 4 by Player 2:
 [[0 2 0]
 [1 2 0]
 [0 1 0]]
Board after move 5 by Player 1:
 [[0 2 0]
 [1 2 1]
 [0 1 0]]
Board after move 6 by Player 2:
 [[0 2 0]
 [1 2 1]
 [0 1 2]]
Board after move 7 by Player 1:
 [[1 2 0]
 [1 2 1]
 [0 1 2]]
Board after move 8 by Player 2:
 [[1 2 2]
 [1 2 1]
 [0 1 2]]
Board after move 9 by Player 1:
 [[1 2 2]
 [1 2 1]
 [1 1 2]]
Winner is Player 1!


1